FROM node:18

# Create app directory
WORKDIR /usr/src/app
# Install pm2 dependencies
RUN npm install pm2 -g
# Bundle app source
COPY . .

# Replace to prod next.config.js
COPY next.config.js.prod next.config.js

# Build app from ts to js
RUN npm install

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]